### PR TITLE
Fix AnyAttribute

### PR DESCRIPTION
**Pull request by blegat**
I guess this was a typo

### CODE REVIEW

**Comment by mlubin** [comment]
We do have an `AbstractSolverInstanceAttribute`, but maybe we should remove this given the recent discussion in #169.

**Comment by blegat** [comment]
Yes, we should discuss this on an issue. The reason of this PR is that since `AbstractSolverInstanceAttribute <: AbstractInstanceAttribute`, using only `AbstractSolverInstanceAttribute` in `AnyAttribute` does not include the attributes that are `AbstractInstanceAttribute` but not `AbstractSolverInstanceAttribute`.
This causes `AnyAttribute` to contain not all attributes.

**Comment by mlubin** [comment]
I'd propose to remove `AbstractSolverInstanceAttribute` completely. And of course replace it with `AbstractInstanceAttribute` in `AnyAttribute`.

**Comment by blegat** [comment]
I am ok with this, done in 407ce2e.

**Comment by mlubin** [comment]
Looks good. Needs a rebase and doc updates.

**Pull request merged**
