### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by mlubin** [comment]
The table doesn't display correctly in the preview, are you sure it's correct?

**Comment by blegat** [comment]
Indeed, it's fixed now :)

**Comment by mlubin** [comment]
There's no parallelism in the meaning of the rows (stable vs. latest/travis vs. codecov?), it's a bit confusing.

**Comment by blegat** [comment]
No, it is in two rows for aesthetic reason, we can do it in one row as in 1b9ec7f1a8af6b5001536166338c6df392973f01 to make it less confusing.

**Pull request merged**
