### PR TITLE
Remove VariableBasisStatus and clarify when NONBASIC_AT_* should be used

### PR DESCRIPTION
**Pull request by mlubin**
Ref https://github.com/JuliaOpt/MathOptInterface.jl/pull/678#issuecomment-466648971
CC @EdvinAblad

### CODE REVIEW

**Comment by mlubin** [comment]
I'm looking at this again and I'm questioning why we have a `VariableBasisStatus()` attribute. Shouldn't this be the `BasisStatus()` on the single-variable constraints instead? As it is currently, this is the only place in MOI where "variable bounds" need to be discussed as a concept, which seems inconsistent.

**Comment by EdvinAblad** [comment]
Consistency is important, however, I think that the most common use case is for a user to query whether a variable is basic or non-basic, not if a constraint is...

Is it possible (and sane) to have both? 
E.g., calling MOI.get(m, MOI.BasisStatus(), var_index), is basically an indirect call to MOI.get(m, MOI.BasisStatus(), var_constr). (where var_constr is the applicable one)

Also I'm not quite sure how these single variable constraints works if they are called multiple times, e.g. x => 0, x >= 3, x =>2. In JuMP they seems to be available from set_lower_bound, in LQOI adding a single-variable bound also (seems to) replace the previous ones. Is it possible for multiple variable bounds to be present? If so, the basis status of the dominated constraints should always return MOI.BASIC (where should this domination check be done, LQOI?).

**Comment by blegat** [comment]
> Is it possible for multiple variable bounds to be present?

No, see https://github.com/JuliaOpt/MathOptInterface.jl/issues/570 The `LowerBoundRef` gives in JuMP gives you the reference of the last bound set

**Comment by mlubin** [comment]
I updated the PR to remove `VariableBasisStatus`. It's not only inconsistent with how we report dual solutions, it's also redundant because you can ask for the `ConstraintBasisStatus` of a `SingleVariable` constraint anyway. Given that there's a direct mapping between the two, we shouldn't force solver interfaces to implement both. Convenience functions can be added at the JuMP level like we do for lower and upper bounds.

@odow @joaquimg

**Pull request merged**
