### PR TITLE
discussion of alternative formulations and what solvers are expected …

### LINKED ISSUE #19: force Nonnegative, Nonpostive, and Zeros to be vector sets
In order to avoid some level of redundancy and extra work for the solver wrappers, I'm thinking that it would be a good idea to disallow (by convention) constraints of the form: ``ScalarAffineFunction`` in  ``Nonnegative(1)``, ``Nonpositve(1)``, or ``Zeros(1)``. These are already covered by the one-dimensional sets ``GreaterThan``, ``LessThan``, and ``EqualTo``.

### LINKED ISSUE #41: Possible redundant problem formulations
Requires a documentation update.

see issues : #40 and JuliaOpt/MathProgBase.jl#186

### PR DESCRIPTION
**Pull request by mlubin**
…to support

Closes #41 
Closes #19 

CC @IssamT @blegat @joaquimg

### CODE REVIEW

**Comment by blegat** [comment]
Why is it so hard to support the nonzero constant ? It is just a matter of a substraction.
For the AffineFunction in Zeros..., I would go further and disallow it. Otherwise we also need to consider ScalarFunction in PSD(1) for example.
I suggest we define AbstractScalarFunction, AbstractVectorFunction, AbstractScalarSet, AbstractVectorSet and define
```julia
addconstraint!(si, ::AbstractVectorFunction, ::AbstractScalarSet) = throw(...)
addconstraint!(si, ::AbstractScalarFunction, ::AbstractVectorSet) = throw(...)
```

**Comment by mlubin** [comment]
> Why is it so hard to support the nonzero constant ? 

There's more complexity involved when you start talking about modifying the set or the constant.

> For the AffineFunction in Zeros..., I would go further and disallow it.

We can't *prevent* a solver from supporting a certain type of constraint. The most we can do is say that by convention there's no need to support it.

**Comment by blegat** [comment]
Yes we cannot prevent it to support. What I suggested was to make it clear
to the user that it is not supported because it is not part of the
interface, not because the solver is missing a method.

**Comment by IssamT** [comment]
When talking about what the solvers need to implement which keep in mind that the user might be annoyed with error messages like this : "Sorry Feature X is not supported by solver Y you have to write it the other way."

Possible use case: 
A user was using a given solver and wrote a lot of models using a some feature and he wanted to test them with another solver. now he is required to patch all models and write them the other way...

This may hurt the power of JuMP being a **unified** modeling language.

I am now not so sure about the conclusion we draw in #40.

**Comment by IssamT** [comment]
Making transformation is though not easy, as @mlubin have often mentioned, and it would be nice to not deal with it at this stage. 

Maybe we can limit a bit the alternative formulations on the interface side and say in the documentation that an MOI solver which supports a type of math programs is required to implement all the related methods?

**Comment by blegat** [comment]
> A user was using a given solver and wrote a lot of models using some feature and he wanted to test them with another solver. now he is required to patch all models and write them the other way...
>
> This may hurt the power of JuMP being a unified modeling language.

We test in the JuMP's tests that all solvers support the features that JuMP needs so that shouldn't happen for JuMP

**Comment by mlubin** [comment]
> When talking about what the solvers need to implement we should keep in mind that the user might be annoyed with error messages like this : "Sorry Feature X is not supported by solver Y you have to write it the other way."

It's obviously inconvenient, but we don't have unlimited resources to implement all possible transformations. We're in the open source world, so I'm hoping that if a feature is missing, users will be motivated to implement it themselves.

**Comment by mlubin** [comment]
I added a discussion higher up about the constant terms.

**Pull request merged**
