### PR TITLE
Fix SemiContinuous for consistency

### PR DESCRIPTION
**Pull request by joaquimg**

### CODE REVIEW

**Comment by mlubin** [comment]
`SemiInteger` is a special case because of the repeated vowel. You're forced to write "semi-integer". All of the other sets like `Semicontinuous`, `Nonnegatives`, `Nonpositives`, can be written like "semicontinuous", "nonnegatives", and "nonpositives". Changing `Semicontinous` to `SemiContinous` would not be consistent with these other sets.

**Comment by odow** [comment]
I'm not a fan of special cases... `Semiinteger` isn't that bad?

**Comment by mlubin** [comment]
It's a special case for the English language, so we're going have an inconsistency either in the name of the set or how we refer to it in the documentation.

**Comment by joaquimg** [comment]
I don´t like `SemiInteger` to be different, looks weird

**Comment by mlubin** [comment]
I won't object to `Semiinteger` if it doesn't bother people

**Comment by joaquimg** [comment]
I like it better

**Comment by mlubin** [comment]
`Semïnteger` anyone?

**Comment by mlubin** [comment]
The diff right now is not quite as intended, I think.

**Comment by joaquimg** [comment]
Would you like `const Semïnteger = Semiinteger` ?

**Comment by mlubin** [comment]
> Would you like ``const Semïnteger = Semiinteger`` ?

I don't think that will be well received, unfortunately.

**Comment by chriscoey** [comment]
semiinteger is fine IMO

**Comment by mlubin** [comment]
We also need a line updating the name in `apireference.md`.

**Comment by mlubin** [comment]
Bump. Needs docs update.

**Pull request merged**
