### PR TITLE
Transform constraint

### PR DESCRIPTION
**Pull request by odow**
Closes https://github.com/JuliaOpt/MathOptInterface.jl/issues/89

### CODE REVIEW

**Comment by blegat** [comment]
Why don't we do
```julia
function transformconstraint!(m::AbstractSolverInstance, c::ConstraintReference{F,S1}, newset::S2)
    f = getattribute(m, ConstraintFunction(), c)
    delete!(m, c)
    addconstraint!(m, f, newset)
end
```
That way, if the solver have something faster to do, it will be called instead.
The user knows that by calling `transformconstraint!` he will always do the most efficient thing.

**Comment by joaquimg** [comment]
That is nice. But then `transformconstraint!` always return a new reference right?

**Comment by blegat** [comment]
How could it return the same reference since it has a different type ?

**Comment by joaquimg** [comment]
Indeed, I got confused with the `modify`. 
A second problem, the solver might not support `delete`, so there must e a `candelete` or `supporttransform`

**Comment by blegat** [comment]
Yes, we could have a
```julia
function cantransformconstraint!(m::AbstractSolverInstance, c::ConstraintReference{F,S1}, newset::S2)
    candelete(m, c)
end
```

**Comment by odow** [comment]
I'm away for a few days. I think we need canmodifyconstraint and cantransformconstraint with the same arguments. Or a better way of throwing errors

**Comment by joaquimg** [comment]
better:
```julia
function cantransformconstraint!(m::AbstractSolverInstance, c::ConstraintReference{F,S1}, newset::S2)
    cangetattribute(m, ConstraintFunction(), c)
    candelete(m, c)
end
```

**Comment by blegat** [comment]
Just need a rebase :)

**Comment by odow** [comment]
Rebased

**Pull request merged**
