### PR TITLE
Include test scripts

### PR DESCRIPTION
**Pull request by joaquimg**
At least we see if there are no weird sintax mistakes

### CODE REVIEW

**Comment by joaquimg** [comment]
How we add MathOptInterfaceUtilities?

**Comment by blegat** [comment]
I am not personally against it but it is going against #104 this change will probably last the time of @mlubin 's vacations :D

**Comment by joaquimg** [comment]
we can wait for him, I just wanted to include the files to check sintax errors

**Comment by joaquimg** [comment]
@mlubin are you against this one after all?

**Comment by mlubin** [comment]
I think we should try as hard as possible to make MOI's runtests not depend on any downstream packages.

**Comment by joaquimg** [comment]
I agree with you. But the idea here is just to load MOI (and nothing else) in runtests so that we avoid some syntax mistakes.

**Comment by mlubin** [comment]
Well we can move the definition of ``isapprox`` back into MOI or duplicate it in the tests folder. Having standalone tests is a sufficient motivation.

**Comment by blegat** [comment]
That is not the only thing being used. IIRC there is also getindex and VectorOfVariables -> VectorAffineFunction conversion

**Comment by mlubin** [comment]
No longer relevant given MOIT

**Pull request closed without merging**
