### PR TITLE
Add tests for using ExprGraphs from NLP evaluators

### PR DESCRIPTION
**Pull request by joehuchette**
Edit(odow): Closes #624

### CODE REVIEW

**Comment by odow** [comment]
Looks like I never got around to finishing https://github.com/JuliaOpt/MathOptInterface.jl/pull/624. 

Tests?

**Comment by joehuchette** [comment]
Ah, didn't see your old PR.

I added some tests for HS071, but I'm not sure if they're exactly what you had in mind. Let me know what you'd like to see.

**Comment by odow** [comment]
I guess I had in mind testing the getting of the expressions.

**Comment by joehuchette** [comment]
@odow Done.

**Comment by joehuchette** [comment]
Not sure why codecov/patch is failing...

**Pull request merged**
