### PR TITLE
Remove julia-06

### PR DESCRIPTION
**Pull request by matbesancon**
Added a Project.toml file with compatible UUID and corresponding dependencies, removed use of Compat

### CODE REVIEW

**Comment by blegat** [comment]
There are also VERSION checks to remove:
```
➜  MathOptInterface git:(master) ✗ grep VERSION * -r
src/functions.jl:@static if VERSION >= v"0.7-"
src/functions.jl:if VERSION < v"0.7-"
src/functions.jl:        if VERSION >= v"0.7-"
src/functions.jl:        if VERSION >= v"0.7-"
src/Utilities/functions.jl:    @static if VERSION >= v"0.7-"
src/Utilities/functions.jl:    @static if VERSION >= v"0.7-"
src/Utilities/functions.jl:@static if VERSION >= v"0.7-"
src/Utilities/model.jl:if VERSION >= v"0.7.0-DEV.2813"
src/Utilities/parser.jl:if VERSION > v"0.7-"
src/Utilities/model.jl.mem:        - if VERSION >= v"0.7.0-DEV.2813"
src/attributes.jl:@static if VERSION >= v"0.7-"
src/Test/modellike.jl:        if VERSION < v"0.7-"
src/Test/modellike.jl:        if VERSION < v"0.7-"
src/Bridges/quadtosocbridge.jl:        @static if VERSION >= v"0.7-"
src/MathOptInterface.jl:VERSION < v"0.7.0-beta2.199" && __precompile__()
src/MathOptInterface.jl:@static if VERSION >= v"0.7-"
test/bridge.jl:        if VERSION < v"0.7-"
test/bridge.jl:        if VERSION < v"0.7-"
test/bridge.jl:        if VERSION < v"0.7-"
test/Utilities/cachingoptimizer.jl:    if VERSION < v"0.7"
test/Utilities/mockoptimizer.jl:    if VERSION < v"0.7-"
test/Utilities/mockoptimizer.jl:    if VERSION < v"0.7-"
test/attributes.jl:        if VERSION < v"0.7-"
```

**Comment by matbesancon** [comment]
Not sure codecov is very meaningful here

**Comment by matbesancon** [comment]
Fixes #661

**Comment by blegat** [comment]
> Not sure codecov is very meaningful here

Not it's know that dropping Julia v0.6 creates a coverage drop: https://github.com/JuliaCI/Coverage.jl/issues/187

**Pull request merged**
