### PR TITLE
implement _result_index_field for NLPBlockDual

### PR DESCRIPTION
**Pull request by rschwarz**
- should fix failure for MINLPTests with Ipopt:
   https://travis-ci.org/JuliaOpt/MINLPTests.jl/builds/603635262

### CODE REVIEW

**Comment by rschwarz** [comment]
Currently testing locally, with MINLPTests.jl

**Comment by rschwarz** [comment]
See also JuliaOpt/Ipopt.jl#182 for where this is already used.

**Comment by mlubin** [comment]
Which attributes need to implement `_result_index_field`? Would an attribute defined outside MOI ever need to implement it?

**Comment by blegat** [comment]
> Which attributes need to implement `_result_index_field`?

Attributes for which the field is not `result_index`, see
https://github.com/JuliaOpt/MathOptInterface.jl/blob/6369fcc478fd0641ad295c2145c30fc38a6b6c0d/src/attributes.jl#L126-L129

> Would an attribute defined outside MOI ever need to implement it?

No, the field should be `result_index` by convention for `check_result_index_bounds` to work. With MOI v0.10, we might remove `_result_index_field` and rename `N` to `result_index` for the attributes for which it is `N`.

**Pull request merged**
