### PR TITLE
Add sizehint! in MOIU canonical

### PR DESCRIPTION
**Pull request by joaquimg**

### CODE REVIEW

**Comment by blegat** [comment]
What is the performance speedup for functions without duplicates ?

**Comment by joaquimg** [comment]
Well this fix is aimed for all functions not only the ones with no duplicate. Is there any harm in that sizehint?

**Comment by blegat** [comment]
If there are lots of duplicates, this might allocate more than needed. So in case we have a performance win when there is only a few duplicates then the increased memory used when there are lots of duplicates is no big deal but otherwise we might reconsider.

**Comment by odow** [comment]
Closing this as stale. It can be re-addressed if, and when, benchmarking shows it as a bottleneck.

**Pull request closed without merging**
