### PR TITLE
Change MultirowChange to VectorCoefficientChange

### PR DESCRIPTION
**Pull request by odow**
For better consistency.

### CODE REVIEW

**Comment by mlubin** [comment]
This name is a bit confusing because the "coefficient" of a vector-valued constraint isn't well defined. If we had a general change that allowed you to modify coefficients for multiple variables in multiple rows, what would it be called?

**Comment by odow** [comment]
What about making it
```julia
struct VectorCoefficientChange{T}
    variables::Vector{VariableReference}
    rows::Vector{Int}
    new_coefficients::Vector{T}
end
```
Solvers can complain if `variables` contains different variable references and they don't support that.

**Comment by mlubin** [comment]
The intention for the single-column change is that it could have a special meaning in the context of column generation, i.e., adding a new variable and then doing a `MultirowChange` could be implemented efficiently. Don't really want to get rid of that.

**Comment by odow** [comment]
Can this be closed?

**Comment by mlubin** [comment]
Yes, if you don't want to bikeshed further.

**Pull request closed without merging**
