### PR TITLE
Make functions generic with respect to variable type

### PR DESCRIPTION
**Pull request by mlubin**
But keep simple names for the functions using VariableReference

https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/pull/22#discussion_r147913099

### CODE REVIEW

**Comment by mlubin** [comment]
I'm doubting this again. MOIU's tests are now failing with:
```julia
Conversion VectorOfVariables -> VectorAffineFunction: Error During Test
  Got an exception of type MethodError outside of a @test
  MethodError: no method matching MathOptInterface.GenericVectorAffineFunction{MathOptInterface.VariableReference,T} where T(::Array{Int64,1}, ::Array{MathOptInterface.VariableReference,1}, ::Array{Int64,1}, ::Array{Int64,1})
  Stacktrace:
   [1] macro expansion at /home/mlubin/.julia/v0.6/MathOptInterfaceUtilities/test/functions.jl:7 [inlined]
   [2] macro expansion at ./test.jl:860 [inlined]
   [3] macro expansion at /home/mlubin/.julia/v0.6/MathOptInterfaceUtilities/test/functions.jl:6 [inlined]
   [4] macro expansion at ./test.jl:860 [inlined]
   [5] anonymous at ./<missing>:?
   [6] include_from_node1(::String) at ./loading.jl:576
   [7] include(::String) at ./sysimg.jl:14
   [8] include_from_node1(::String) at ./loading.jl:576
   [9] include(::String) at ./sysimg.jl:14
   [10] process_options(::Base.JLOptions) at ./client.jl:305
   [11] _start() at ./client.jl:371
```
because
```julia
function MOI.VectorAffineFunction{T}(f::MOI.VectorOfVariables) where T
    n = length(f.variables)
    MOI.VectorAffineFunction(collect(1:n), f.variables, ones(T, n), zeros(T, n))
end
```
doesn't do the same thing anymore. Also the generic names will always leak through error messages.

**Comment by blegat** [comment]
We could define the constructor `VectorAffineFunction` in MOI to make it transparent.

**Comment by mlubin** [comment]
@blegat, the transparency is a lie because the generic names will always appear in error messages. If you have a strong objection to #158, comment there.

**Comment by blegat** [comment]
No objection, your argument makes sense

**Pull request merged**
