### PR TITLE
Add duplicate terms to linear part of objective in qp2test

### PR DESCRIPTION
**Pull request by tkoolen**
To catch https://github.com/JuliaOpt/Gurobi.jl/pull/125#issuecomment-406017666, https://github.com/JuliaOpt/Xpress.jl/issues/22, https://github.com/JuliaOpt/GLPK.jl/issues/57.

### CODE REVIEW

**Comment by tkoolen** [comment]
cc:@rdeits.

**Comment by odow** [comment]
It would be better to write a new unit test for this. We are trying to move away from these big tests

**Comment by joaquimg** [comment]
You can do something along the lines of solve_qcp_edge_cases

**Comment by tkoolen** [comment]
Superseded by #432 (thanks!).

**Pull request closed without merging**
