### PR TITLE
Add AbstractScalarFunction and AbstractVectorFunction

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by mlubin** [comment]
Why is this extra level of abstraction needed?

**Comment by blegat** [comment]
I wouldn't say it is needed but it might be helpful to the solver wrappers. For example they might want to do:
```julia
addconstraint!(m::..., f::AbstractScalarFunction, s) = addconstraint!(m, MOI.vectorize(f), MOI.vectorize(s))
```
so that they do not need to implement the scalar versions.

**Comment by mlubin** [comment]
That's not quite correct because the constraint references will be of the wrong type.

**Comment by mlubin** [comment]
I feel like this is better defined as `Union{ScalarVariablewiseFuncton,ScalarAffineFunction,...}` directly in the solver interface, rather than adding an extra level to the type hierarchy in MOI.

**Comment by mlubin** [comment]
I'm going to close this for now.

**Pull request closed without merging**
