### PR TITLE
Define operate and refactor moivcat

### PR DESCRIPTION
**Pull request by blegat**
Bridges need to do some arithmetic operations like `vcat`, `+`, `-`, ... and need to be able to determine the result of such operation to determine which constraints the bridge generate at compile time.
To achieve this, this PR suggest to define `operate(op::Function, ::Type{T}, args...) that does the operation `op(args...)` with coefficient type `T` and `promote_operation` that gives the type of the output the function `operate` without the need for Julia's inference system.

Currently most bridges only work when the function is `VectorAffineFunction` and convert `VectorOfVariables` to `VectorAffineFunction` while they could also work with `VectorQuadraticFunction` and keep `VectorAffineFunction` unconverted would allow the bridge to create `VectorAffineFunction` functions which could be handled more efficiently by the solver.
Using these functions instead of hardcoding the operations for `VectorAffineFunction` would allow to easily build bridges that work for *any* `AbstractVectorFunction` as input (just like SplitIntervalBridge currently).

### CODE REVIEW

**Comment by blegat** [comment]
Ready for review, I am not planning to do any more changes :)

**Comment by blegat** [comment]
> What's the argument for creating our own operator?

We want `[a, b]` where `a` and `b` and `ScalarAffineFunction` to be a `Vector{ScalarAffineFunction}`, not a `VectorAffineFunction` so we define `moivcat` which is now `MOI.operate(vcat, ...)`.
Same thing for `getindex` and `eachscalar` except that for `getindex` we might still use `eachscalar` and not `operate` as `eachscalar` may allow doing some caching to speed up (see https://github.com/JuliaOpt/MathOptInterface.jl/issues/418#issuecomment-403277617).
What would we do for the call `(+, - or *)(::MOI.SingleVariable, MOI.SingleVariable)`, which coefficient type do we use for the result ?

When doing `a * b` in JuMP we have the issue that we don't know if we can overwrite `a` so we have to copy it. Here we have `operate!` and `operate` so the user can use `operate!` if he knows the first argument can be overwritten.

In MOI we do not care too much about being super-user friendly (user friendly is enough).
In JuMP we need to be super-user friendly so we are forced to implement the `Base` methods,
here we have the choice and we can choose to be more explicit about inplace/coefficient type rather than being super-user friendly.

> type promotion system?

`Base.promote_op` should not be used
https://github.com/JuliaLang/julia/pull/26344#issuecomment-371613750

**Comment by blegat** [comment]
As a second thought, it would indeed be nice to also define `Base.:+`, ... methods using `operate`

**Comment by mlubin** [comment]
> We want [a, b] where a and b and ScalarAffineFunction to be a Vector{ScalarAffineFunction}, not a VectorAffineFunction so we define moivcat which is now MOI.operate(vcat, ...).

I wonder if using a macro to switch the context could be useful. Like `[a, b]` returns `Vector{ScalarAffineFunction}` and `@MOI.operate [a, b]` returns `VectorAffineFunction`. But not needed immediately.

**Pull request merged**
