### PR TITLE
Prepare NEWS for MOI v0.6.2

### PR DESCRIPTION
**Pull request by blegat**
I have used unicode symbols to help the user distinguish between bug fixes (🐛), performance improvements (⚡️), usability improvements (🚸) and new features (✨).

### CODE REVIEW

**Comment by joaquimg** [comment]
Using them consistently means using them always in the news.md right? And not making it mandatory in commits right?

I like these emojis, I am not 100% convinced. Certainly this classification is very good.

Will it generate a dependency? If the emojis change it will affect older news.md?

**Comment by mlubin** [comment]
The division into bug fixes/performance/new features is useful, but I think a similar benefit with less indirection could be gained by writing the words out explicitly as @odow suggested.

**Comment by ccoffrin** [comment]
I'll also vote for words over icons.  But still a stalwart supporter of gitmoji in commits and PRs.

**Comment by blegat** [comment]
The division can be done in a separate PR that does it for all NEWS.md items

**Pull request merged**
